# Generated by Django 2.1.2 on 2019-01-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
