# Generated by Django 2.1.2 on 2019-01-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20190112_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.TextField(default='notsold', max_length=50),
        ),
    ]
