# Generated by Django 2.1.2 on 2019-01-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mobile',
            field=models.IntegerField(blank=True, default=777777777),
        ),
    ]
