# Generated by Django 2.1.2 on 2019-01-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_item_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='mobile',
        ),
    ]
