# Generated by Django 2.1.2 on 2019-01-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_item_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(blank=True, default=888888888),
        ),
    ]
